import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Download, ArrowLeft, CheckCircle2, Calendar, Stethoscope, FlaskConical, Pill, FileText, ClipboardList, Share2, Link, Mail, Loader2 } from 'lucide-react';
import { PatientAnalysisResult, TimelineEvent } from '../types';

interface ReportViewProps {
  result: PatientAnalysisResult;
  onReset: () => void;
}

const getCategoryIcon = (category: string) => {
  switch (category.toLowerCase()) {
    case 'lab': return <FlaskConical className="w-5 h-5 text-purple-500" />;
    case 'consultation': return <Stethoscope className="w-5 h-5 text-blue-500" />;
    case 'medication': return <Pill className="w-5 h-5 text-red-500" />;
    case 'procedure': return <Activity className="w-5 h-5 text-amber-500" />;
    default: return <FileText className="w-5 h-5 text-slate-500" />;
  }
};

const getCategoryColor = (category: string) => {
  switch (category.toLowerCase()) {
    case 'lab': return 'bg-purple-100 border-purple-200';
    case 'consultation': return 'bg-blue-100 border-blue-200';
    case 'medication': return 'bg-red-100 border-red-200';
    case 'procedure': return 'bg-amber-100 border-amber-200';
    default: return 'bg-slate-100 border-slate-200';
  }
};

export const ReportView: React.FC<ReportViewProps> = ({ result, onReset }) => {
  const { summary, timeline } = result;
  const [showShareMenu, setShowShareMenu] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  useEffect(() => {
    // Set a print-friendly title
    const originalTitle = document.title;
    document.title = "MediSynth_Clinical_Summary_" + new Date().toISOString().split('T')[0];
    
    return () => {
      document.title = originalTitle;
    };
  }, []);

  const handleDownloadPDF = async () => {
    setIsGeneratingPdf(true);
    
    const originalElement = document.getElementById('report-container');
    if (!originalElement) {
        setIsGeneratingPdf(false);
        return;
    }

    // Create a clone to manipulate for PDF generation without affecting UI
    // This ensures we get a clean "document" look rather than a screenshot of the UI card
    const clone = originalElement.cloneNode(true) as HTMLElement;
    
    // Style the clone for optimal A4 pdf generation
    Object.assign(clone.style, {
        width: '800px', // Fixed width for consistent A4 scaling
        height: 'auto',
        overflow: 'visible',
        position: 'absolute',
        top: '-9999px',
        left: '-9999px',
        background: 'white',
        color: 'black',
        padding: '20px' // Add padding to the container itself
    });
    
    // Remove UI-specific styles that don't translate well to print
    clone.classList.remove('shadow-xl', 'rounded-3xl', 'border', 'lg:col-span-2');
    clone.classList.add('w-full');

    // Force text color to black for better readability in PDF
    const textElements = clone.querySelectorAll('*');
    textElements.forEach((el: any) => {
        // Keep pills colored, but text black
        if (!el.className.includes('bg-')) {
             el.style.color = '#000000';
        }
    });

    // Append to body to allow html2pdf to render it
    document.body.appendChild(clone);

    const opt = {
      margin: [15, 15, 15, 15], // Standard document margins (mm)
      filename: `MediSynth_Report_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { 
          scale: 2, // High resolution
          useCORS: true, 
          letterRendering: true,
          scrollY: 0,
          windowWidth: 800
      },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
    };

    try {
      // @ts-ignore - html2pdf is loaded via script tag in index.html
      if (window.html2pdf) {
        // @ts-ignore
        await window.html2pdf().set(opt).from(clone).save();
      } else {
        window.print();
      }
    } catch (error) {
      console.error("PDF Generation failed", error);
      alert("Failed to generate PDF. Falling back to print mode.");
      window.print();
    } finally {
      // Clean up
      document.body.removeChild(clone);
      setIsGeneratingPdf(false);
    }
  };

  const handleCopyLink = () => {
    const dummyLink = `https://medisynth.ai/share/${Math.random().toString(36).substring(7)}`;
    navigator.clipboard.writeText(dummyLink);
    setShowShareMenu(false);
    alert(`Secure link copied to clipboard:\n${dummyLink}`);
  };

  const handleEmailShare = () => {
    const subject = "MediSynth Clinical Summary";
    const body = `Please review the attached clinical summary generated by MediSynth AI.\n\nSummary Preview:\n${summary.substring(0, 300)}...\n\nLogin to view full report.`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    setShowShareMenu(false);
  };

  return (
    <>
      <style>{`
        @media print {
          @page { margin: 1.5cm; size: auto; }
          html, body, #root, main { height: auto !important; overflow: visible !important; background: white !important; }
          nav, footer, .no-print, button { display: none !important; }
          #report-container { box-shadow: none !important; border: none !important; width: 100% !important; max-width: none !important; }
          #timeline-column { display: none !important; }
          .prose { max-width: 100% !important; color: black !important; }
        }
      `}</style>

      <div id="main-layout" className="animate-fade-in-up grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Main Report Column */}
        <div id="report-container" className="lg:col-span-2 bg-white rounded-3xl shadow-xl border border-slate-100 overflow-hidden flex flex-col">
          {/* Header Section */}
          <div className="bg-slate-900 text-white p-8 relative overflow-hidden flex-shrink-0">
              <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500 rounded-full mix-blend-multiply filter blur-3xl opacity-20 -translate-y-1/2 translate-x-1/3 no-print"></div>
              <div className="relative z-10">
                  <div className="flex items-center gap-3 mb-4 no-print">
                      <div className="bg-green-500/20 text-green-400 p-2 rounded-full">
                          <CheckCircle2 className="w-6 h-6" />
                      </div>
                      <span className="font-semibold text-green-400 tracking-wide uppercase text-sm">Analysis Complete</span>
                  </div>
                  <h2 className="text-3xl font-bold text-white mb-2">Clinical Synthesis</h2>
                  <p className="text-slate-400 max-w-xl">
                      Comprehensive AI-generated summary derived from patient documentation.
                  </p>
              </div>
          </div>

          {/* Markdown Content */}
          <div id="report-content" className="p-8 sm:p-12 flex-grow">
              <article className="prose prose-slate max-w-none prose-headings:text-slate-800 prose-headings:font-bold prose-p:text-slate-600 prose-li:text-slate-600 prose-strong:text-slate-800 prose-a:text-blue-600">
                  <ReactMarkdown>{summary}</ReactMarkdown>
              </article>

              {/* Actions Footer - Ignored by html2pdf via data-html2canvas-ignore */}
              <div className="mt-12 pt-8 border-t border-slate-100 flex flex-col sm:flex-row gap-4 justify-between items-center no-print" data-html2canvas-ignore>
                  <button 
                      onClick={onReset}
                      className="flex items-center gap-2 text-slate-500 hover:text-slate-800 transition-colors font-medium px-4 py-2"
                  >
                      <ArrowLeft className="w-4 h-4" />
                      New Analysis
                  </button>

                  <div className="flex items-center gap-3">
                    {/* Share Button Dropdown */}
                    <div className="relative">
                      <button 
                        onClick={() => setShowShareMenu(!showShareMenu)}
                        className="flex items-center gap-2 bg-white text-slate-700 border border-slate-200 px-5 py-3 rounded-xl font-medium shadow-sm hover:bg-slate-50 hover:border-slate-300 transition-all"
                      >
                        <Share2 className="w-4 h-4" />
                        Share
                      </button>

                      {showShareMenu && (
                        <>
                          <div className="fixed inset-0 z-10" onClick={() => setShowShareMenu(false)}></div>
                          <div className="absolute bottom-full right-0 mb-2 w-48 bg-white rounded-xl shadow-xl border border-slate-100 overflow-hidden z-20 animate-fade-in-up">
                            <button 
                              onClick={handleCopyLink}
                              className="w-full text-left px-4 py-3 hover:bg-slate-50 flex items-center gap-3 text-sm text-slate-700 transition-colors"
                            >
                              <Link className="w-4 h-4 text-slate-400" />
                              Copy Link
                            </button>
                            <div className="h-px bg-slate-50"></div>
                            <button 
                              onClick={handleEmailShare}
                              className="w-full text-left px-4 py-3 hover:bg-slate-50 flex items-center gap-3 text-sm text-slate-700 transition-colors"
                            >
                              <Mail className="w-4 h-4 text-slate-400" />
                              Send Email
                            </button>
                          </div>
                        </>
                      )}
                    </div>

                    <button 
                        className="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-xl font-medium shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all disabled:opacity-70 disabled:cursor-wait"
                        onClick={handleDownloadPDF}
                        disabled={isGeneratingPdf}
                    >
                        {isGeneratingPdf ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                        {isGeneratingPdf ? 'Generating...' : 'Export to PDF'}
                    </button>
                  </div>
              </div>
          </div>
        </div>

        {/* Timeline Column */}
        <div id="timeline-column" className="lg:col-span-1 no-print">
          <div className="bg-white rounded-3xl shadow-lg border border-slate-100 p-6 sticky top-6 max-h-[calc(100vh-3rem)] overflow-y-auto custom-scrollbar">
            <div className="flex items-center gap-2 mb-6 pb-4 border-b border-slate-100">
               <ClipboardList className="w-6 h-6 text-blue-500" />
               <h3 className="text-xl font-bold text-slate-800">Patient Timeline</h3>
            </div>

            {timeline.length === 0 ? (
              <div className="text-center p-8 text-slate-400 bg-slate-50 rounded-xl">
                <Calendar className="w-10 h-10 mx-auto mb-2 opacity-50" />
                <p>No dated events found in documents.</p>
              </div>
            ) : (
              <div className="relative pl-2">
                {/* Vertical line */}
                <div className="absolute top-2 bottom-0 left-[21px] w-0.5 bg-slate-200"></div>

                <div className="space-y-6">
                  {timeline.map((event, index) => (
                    <div 
                      key={index} 
                      className={`timeline-item relative pl-12`}
                      style={{ animationDelay: `${index * 0.15}s` }}
                    >
                      {/* Dot */}
                      <div className={`absolute left-2 top-3 w-6 h-6 rounded-full border-4 border-white shadow-sm flex items-center justify-center z-10 timeline-dot ${
                          index === 0 ? 'bg-blue-500 scale-110' : 'bg-slate-300'
                      }`}>
                          {index === 0 && <div className="w-2 h-2 bg-white rounded-full"></div>}
                      </div>

                      {/* Card */}
                      <div className={`p-4 rounded-2xl border transition-all duration-300 hover:shadow-md ${getCategoryColor(event.category)} bg-opacity-50 border-opacity-60`}>
                        <div className="flex justify-between items-start mb-1">
                          <span className="text-xs font-bold uppercase tracking-wider text-slate-500 bg-white/60 px-2 py-0.5 rounded-md">
                            {event.date}
                          </span>
                          {getCategoryIcon(event.category)}
                        </div>
                        <h4 className="font-bold text-slate-800 text-sm">{event.title}</h4>
                        {event.description && (
                          <p className="text-sm text-slate-600 mt-1 leading-snug">{event.description}</p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

      </div>
    </>
  );
};

// Helper Icon for Default case in reportview
function Activity(props: any) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
      </svg>
    )
  }